<?php
ini_set("magic_quotes_gpc", "off");
ini_set('memory_limit', '128M');
ini_set('max_execution_time', '900');
ini_set('upload_max_filesize', '8M');
set_time_limit (600);
date_default_timezone_set('Europe/Kiev');

define('DEVEL', 0);

define('DBHOST', 'localhost');
define('DBUSER', '[db_user]');
define('DBPASS', '[db_pass]');
define('DBNAME', '[db_name]');
define('DB_PREFIX', '');
define('SITE_URL', 'http://yourdomain');
define('SITE_NAME', 'Adressbook');
define('ROOT', dirname(__FILE__) . DIRECTORY_SEPARATOR);
define('KERNEL', ROOT . 'system' . DIRECTORY_SEPARATOR);
define('DIR_CACHE', KERNEL . 'cache' . DIRECTORY_SEPARATOR);
define('SITE', ROOT . 'site' . DIRECTORY_SEPARATOR);
define('VIEWS', SITE . 'views' . DIRECTORY_SEPARATOR);
define('LANGUAGE', SITE . 'language' . DIRECTORY_SEPARATOR);
define('DEFAULT_LANGUAGE_PATH', 'en_US/english');
define('PAGE_LIMIT', 10);
define('IMAGE_FILES', ROOT . 'images' . DIRECTORY_SEPARATOR);
define('IMAGE_URL', SITE_URL . DIRECTORY_SEPARATOR . 'images' . DIRECTORY_SEPARATOR);
define('ADMIN', ROOT . 'backend' . DIRECTORY_SEPARATOR);
define('A_SITE_URL', SITE_URL . '/backend'); 
define('A_VIEWS', ADMIN . 'views' . DIRECTORY_SEPARATOR);
define('A_LANGUAGE', ADMIN . 'language' . DIRECTORY_SEPARATOR);
define('ERROR_ROUTE', 'notfound');
define('DEFAULT_ROUTE', 'index');
define('DEFAULT_AJAX_ROUTE', 'index/container');
define('MAIL', 'andriy.yun@gmail.com');
define('TECH_MAIL', 'ayu@deweb.com.ua');
ini_set('session.gc_maxlifetime', 120960);
ini_set('session.cookie_lifetime', 120960);
ini_set('session.save_path', ROOT .'sessions');
include(KERNEL . 'class.mysql.php'); 
include(KERNEL . 'functions.php');
include(KERNEL . 'class.load.php');
include(KERNEL . 'class.action.php');
include(KERNEL . 'class.front.php');
include(KERNEL . 'class.registry.php');
include(KERNEL . 'class.request.php');
include(KERNEL . 'class.language.php');
include(KERNEL . 'class.session.php');
include(KERNEL . 'class.user.php');
include(KERNEL . 'class.cache.php');
include(KERNEL . 'class.image.php');
include(KERNEL . 'class.document.php');
include(KERNEL . 'class.model.php');
include(KERNEL . 'class.controller.php');
include(KERNEL . 'class.view.php');